FIX: Add, delete and copy buttons were visible in map view
origam/origam-html pull request #247
Opened 2021-09-21 12:52 UTC by JindrichSusen

2021-09-21 19:05 UTC, washibana requested changes

2021-09-21 19:05 UTC, washibana commented on src/model/selectors/DataView/getActivePerspective.ts
> +import {getDataView} from "model/selectors/DataView/getDataView";
There's a missing license info.

2021-09-22 07:04 UTC, JindrichSusen commented on src/model/selectors/DataView/getActivePerspective.ts
> +import {getDataView} from "model/selectors/DataView/getDataView";
Almost no files have license info in 2021.1. They were added to master only.

2021-09-22 07:28 UTC, washibana approved these changes

2021-09-22 07:28 UTC, merged