Plugins
origam/origam-html pull request #94
Opened 2021-06-18 11:15 UTC by JindrichSusen

2021-06-23 07:53 UTC, ptomask commented on src/gui/Components/ScreenElements/DataViewToolbar.module.css
> +  border: 1px solidvar(--black);
```suggestion
  border: 1px solid var(--black);
```

2021-06-23 08:22 UTC, ptomask commented on src/gui/Components/Dialog/Dialog.module.scss
> +  background-color: rgba(var(--black), 0.055);
**PLEASE FIX ON OTHER PLACES WHERE `rgb(var(` or `rgba(var(` IS USED AS WELL**
I am going to comment only on this place.

This will not unfortunately work, `rgba(...)` accepts only 4 decimal arguments. Some nice article about this topic here: https://medium.com/techhive-io/how-to-use-css-variables-with-sass-mixins-671e1f6067b3

Either we can use whole `rgba...` expression as a color definion (e.g. `--black: rgba(#0d0d0d, 0.055)` ) , but this leads to many colors being defined if we have many different alpha levels used. By the way, this works, because SASS compiler translates the hex value to the rgb tuple, which cannot be done if we use css variable.

Or we can use the suggested way. I just did some proof of concept and it should work with our stack. So something like this:

```
@function hexToRGB($hex) {
  @return red($hex), green($hex), blue($hex);
}

$black: #0d0d0d;
:root {
  --black: $black;
  --black-rgb: #{hexToRGB($black)};
}

.someClass1 {
  background-color: rgba(var(--black-rgb), 0.3);
  color: white;
}
```

Or come with your own. I can already see some potential issue as we are going to implement runtime color change as we will have to switch both `--...color...` and `--...color-rgb...` versions. Can be done of course, but we shall not forget about it...

2021-06-23 08:30 UTC, ptomask commented on src/gui/Components/PublicComponenets/SimpleDropdown.tsx
> +            onClick={() => this.isDropped = !this.isDropped}
Just remember the native dropdowns (`<select>...`) open and close by `mousedown` event, not `click` on their trigger area. I do not know the primary motivation for this, and this shall not be a problem so far on this place.

2021-06-23 08:50 UTC, ptomask commented on src/gui/Components/PublicComponenets/SimpleDropdown.tsx
>  }> {
As far as I can see, the dropdown will not close when you click outside of it. There shall be `mousedown` handler registered on `window` when it gets dropped down and removed when it is getting closed. 

Also I found using `mousewheel` event to close the dropdown convenient as well, because despite the fact `<DropdownLayout...` components trying to do their best to keep the control position, it might not be always the case. Also closing dropdowns as you scroll something outside of them is a native behaviour so users shall be used to it.

Last but not least if you implement `window.addEventListener('mousedown'....` and `window.addEventListener('mousewheel'...` you need to check whether the interaction does not happen on the dropdown itself, which would collide with its own internal logic (e.g. scrolling its dropped down body would close it). I use `someDomElement.contains(anotherDomElement)` successfully.

I just realized this is already implemented - You can use `onDropupRequest` - see https://github.com/origam/origam-html/blob/a7d8811ea72144474d8d12921d72a33b600e58b0/src/modules/Editors/DropdownEditor/Dropdown/DropdownLayout.tsx#L96 

.... But it does not look to handle `mousedown` events outside to close it either 🤔

2021-06-23 08:51 UTC, ptomask commented on src/gui/Components/ScreenElements/DataViewLoading.module.css
> +  border: 1px solidvar(--white);
```suggestion
  border: 1px solid var(--white);
```

2021-06-23 08:51 UTC, ptomask commented on src/gui/Components/ScreenElements/DataViewLoading.module.css
> +  border: 1px solidvar(--white);
```suggestion
  border: 1px solid var(--white);
```

2021-06-23 08:53 UTC, ptomask commented on src/gui/Workbench/ScreenArea/FormView/FormField.module.css
> +  border: 1px solidvar(--black);
```suggestion
  border: 1px solid var(--black);
```

2021-06-23 08:59 UTC, ptomask commented on src/gui/Components/ScreenElements/Table/PositionedField.module.css
> +ORIGAM is free software: you canvar(--red)istribute it and/or modify
Big LMAO on this...
🤣🤣🤣🤣🤣🤣🤣

You might like to tune up your regexes better :)

Please fix similar issues if happened elsewhere.

```suggestion
ORIGAM is free software: you can redistribute it and/or modify
```

2021-06-23 09:02 UTC, ptomask commented on src/gui/Components/Splitter/Splitter.module.scss
> +ORIGAM is free software: you canvar(--red)istribute it and/or modify
```suggestion
ORIGAM is free software: you can redistribute it and/or modify
```

2021-06-23 09:03 UTC, ptomask commented on src/gui/Components/TabbedView/TabbedViewHandleRow.module.scss
> +  border-bottom: 2px solidvar(--white);
```suggestion
  border-bottom: 2px solid var(--white);
```

2021-06-23 09:04 UTC, ptomask commented on src/gui/Workbench/ScreenArea/FormScreen.module.css
> +  /* border: 1px solidvar(--black);*/
Yes, it is commented out, but....

```suggestion
  /* border: 1px solid var(--black);*/
```

2021-06-23 09:10 UTC, ptomask commented on src/gui/Workbench/ScreenArea/FormScreenBuilder.tsx
> +      if (xso.attributes.Type === "FormLevelPlugin" ||
This is very much context dependent and probably correct, but only as a side note I would pass at least the whole `xso` to the plugins and let them form some kind of *Chain of Responsibility* . This way you would make any plugin able to put its own content instead of the original content without any need of explicitly telling them so in the Architect. I would appreciate this feature, but it is maybe unwanted for some good reason (e.g. giving the plugins too much power.... which they already seem to have anyway....) .

2021-06-23 09:11 UTC, ptomask commented on src/gui/Workbench/ScreenArea/FormScreenBuilder.tsx
> +        getFormScreenLifecycle(self.formScreen);
Just out of curiosity: Why?

2021-06-23 09:25 UTC, ptomask commented on src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx
> +        dataView.clear()
This is going to clear the data received from `InitUI` api call for non-paginated screens and we want this to happen, right?

2021-06-23 09:28 UTC, ptomask commented on src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx
> +          throw new Error(`Plugin ${node.attributes.Name} is not FormLevelPlugin`)
Maybe I would let it fail sooner, maybe even during compilation time, maybe even not let this happen in the Architect, because this signals the plugin is installed where it should not... what do you think?

2021-06-23 09:34 UTC, ptomask commented on src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx
> +        const formPlugin = plugin as IFormPlugin;
I think `formPlugin` shall already be typed as `IFormPlugin` because `isIFormPlugin` is a typeguard. See https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

2021-06-23 09:41 UTC, ptomask commented on src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx
> +        sectionPlugin.getFormParameters = () => JSON.parse(JSON.stringify(this.parameters));
Here this probably works fine, but remember it might be generally lossy. 

You can use `lodash`es `cloneDeep` if the deep copy is really needed. 

Maybe we are fine with shallow copy, so: `{...this.parameters}`. 

Or we can maintain some immutable culture - that is why `immer`s `produce` is/was used on some places (which shall automatically freeze the whole structure being "modified").

2021-06-23 09:44 UTC, ptomask commented on src/model/entities/ListRowContainer.ts
>    appendRecords(rowsIn: any[][]){
This method will always fail. Is the universum ready for that? 🦄

2021-06-23 09:46 UTC, ptomask commented on src/modules/DataView/Perspective/MapPerspective/MapPerspectiveUI.module.scss
> +    border: 2px solidvar(--yellow);
```suggestion
    border: 2px solid var(--yellow);
```

2021-06-23 09:46 UTC, ptomask commented on src/modules/DataView/Perspective/MapPerspective/MapPerspectiveUI.module.scss
> +  border: 1px solidvar(--black);
```suggestion
  border: 1px solid var(--black);
```

2021-06-23 09:56 UTC, ptomask commented on src/modules/Editors/DropdownEditor/Dropdown/DropdownLayoutBody.tsx
> +  props: PropsWithChildren<{ render: () => React.ReactNode, minSideMargin: number }> = {render: ()=> null, minSideMargin: 50}
This will not let us to omit `minSideMargin` in the props, it needs to be declared as optional. No bug, just to note.

2021-06-23 10:02 UTC, ptomask commented on src/plugins/implementations/AuditPlugin.tsx
> +      localizer={new Localizer(localizations, "en-US")}/>;
Will be always EN locales. Is this what we want?

2021-06-23 10:04 UTC, ptomask commented on src/plugins/implementations/AuditPlugin.tsx
> +      <>
`key` property shall be used here.

2021-06-23 10:05 UTC, ptomask commented on src/plugins/implementations/AuditPlugin.tsx
> +    return this.propertiesToRender.map(property =><div className={S.column}>{this.dataView.getCellText(row, property.id)}</div>)
`key` property shall be used here.

2021-06-23 10:06 UTC, ptomask commented on src/plugins/implementations/AuditPlugin.tsx
> +            .map(row => <div className={S.row}>{this.renderRow(row as any[])}</div>)}
`key` property shall be used here.

2021-06-23 10:08 UTC, ptomask commented on src/plugins/implementations/FilterPlugin.module.scss
> +  justify-content: space-between
```suggestion
  justify-content: space-between;
```

2021-06-23 10:14 UTC, ptomask commented on src/plugins/implementations/FilterPlugin.tsx
> +  plugin = this.props.filterPlugin;
This will be set once before the constructor gets called. I expect `filterPlugin` is already known and constant, but generally better would be:

```suggestion
  get plugin() {
      return this.props.filterPlugin;
  }
```

2021-06-23 10:18 UTC, ptomask commented on src/plugins/tools/Localizer.ts
> +      localization = this.localizations.find(localization => localization.locale === locale.split("-")[0]);
I have seen locale ids with different casing , e.g. both `en-US` / `en-us` if we are sure we use this consistently, then ok, but otherwise consider lower/upper -casing them before this comparison.

2021-06-23 10:24 UTC, ptomask requested changes
Generally ok, but see the comments.

2021-06-24 14:29 UTC, JindrichSusen commented on src/gui/Workbench/ScreenArea/FormScreenBuilder.tsx
> +      if (xso.attributes.Type === "FormLevelPlugin" ||
There was an explicit requirement that the user should position the plugins in the Architect. Replacing random gui elements by the plugins was seen as too much of magic.

2021-06-24 14:32 UTC, JindrichSusen commented on src/gui/Workbench/ScreenArea/FormScreenBuilder.tsx
> +        getFormScreenLifecycle(self.formScreen);
No. I did not call the getter function to get some kind of side effect. I just forgot it there.

2021-06-24 14:45 UTC, JindrichSusen commented on src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx
> +        dataView.clear()
Good point. This should only happen for DataViews of ScreenLevelPlugins. I will move the call to clear.

2021-06-24 14:52 UTC, JindrichSusen commented on src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx
> +          throw new Error(`Plugin ${node.attributes.Name} is not FormLevelPlugin`)
This should check that the type of plugin defined in the Architect matches the type in javascript. We need the xml node and the plugin instance to check that so I don't think we can do that any sooner.

2021-06-24 14:57 UTC, JindrichSusen commented on src/model/entities/FormScreenLifecycle/FormScreenLifecycle.tsx
> +        const formPlugin = plugin as IFormPlugin;
Yest the cast is redundant

2021-06-24 16:14 UTC, JindrichSusen commented on src/plugins/implementations/AuditPlugin.tsx
> +      localizer={new Localizer(localizations, "en-US")}/>;
The constructor parameter set here is called "defaultLocale" it represents the locale used for the translation if the active translation set does not have the requested key. I thought it would be better to try to display something than to throw an exception because that is the behavior we have in our "T" translation function. But of course if the key is not even in the default transtaltions an exception will be thrown.

2021-06-24 16:35 UTC, JindrichSusen commented on src/plugins/implementations/FilterPlugin.tsx
> +  plugin = this.props.filterPlugin;
This was ment to be just a shorthand. Why is it better to use a getter here? Do you mean that some could try to change it while it should be a constant?
whar about:
 private readonly plugin = this.props.filterPlugin;

2021-07-06 09:19 UTC, ptomask approved these changes

2021-07-06 09:19 UTC, merged